# Generated by Django 4.0.5 on 2022-06-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_appemailusercredentialsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='appemailusercredentialsmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appemailusercredentialsmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
